### ISSUE TITLE
[Possible] Review Bug

### ISSUE THREAD

**Issue by pepijn809** [senpaiski/TopAnimeStream#26]
I don't seem to be able to submit a review properly. 
Could be a bug. I will try again tomorrow, perhaps with a different device or so. 

To tired now xD

**Comment by senpaiski** [comment]
This and recommendations submit doesn't seems to work when you have already did a partial post back of the page. I will fix it.

Thanks for reporting :D

**Comment by senpaiski** [comment]
I've publish a bunch of fixes today. Tell me if it's working on your side.

**Comment by pepijn809** [comment]
I will check it today ;)

**Comment by pepijn809** [comment]
It works on my end. Sorry, i've been so busy. Finally done with school, so that's great :)
