### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by Draxler** [senpaiski/TopAnimeStream#27]
I saw that website had a big update, so i want to see if app stil works because of that update. It turns out that app is indeed unusable since loging into app isn't working. I realy hope this app would still be available to use.

**Comment by senpaiski** [comment]
You are correct! Both the desktop and android device app are now deprecated. 
I don’t have plans to make a new desktop app version, so you will have to use the website. You should try it! The website is now essentially the app but with a lot of bug fixes and new features.

As for the android app, I have somebody working on it and It should be released by the end of January 2016.

**Comment by Draxler** [comment]
I kinda hoped you would updated desktop app as well. I can't understand why would you kill desktop app.
This new website, it's not for me (no offense) .. 
I rely liked TopAnimeStream Website (as it was) and loved desktop app. Now both is kinda gone for me.. :(
I hope you would reconsider regarding desktop app.

**Comment by senpaiski** [comment]
The website is working the same way as the desktop app was working. I don't see why I should double my work to achieve the same thing. Anyway, I'm kind of alone in this project and I have a big to do list to complete with limited time. I just can't create new features, fix bugs & update both the website and the desktop app at the same time.

If you don't mind, can you tell me why is the new website not for you? 
I would greatly appreciate it if you can give me some feedback.

**Comment by Draxler** [comment]
It's ''all-white'' website (way to bright-to me anyway), it feels really confusing and uncomfortable. Not the place where i could hang to long. Imo, it would be good idea to be at least consistent with the design=colors you had all this time for TopAnimeStream. Blue color is now completely excluded (absent) from your website. You could use at least similar colors as your app have, considering you are using app layout for your website.. (or at least add some colors to this Lite theme / and having second theme - Dark theme would be also good idea.) 

App have really nice chosen colors, all came together really good and app it self performed really nicely. I also didn't find any bugs until this login issue, so there were no need to desabled app until app it self would break down on it's own.
I also do understand your decisions around this project, since you work alone on this project.
Anyway, i'm going to miss TopAnimeStream app.
I wish you much luck with your project ..

**Comment by senpaiski** [comment]
This platform is unique and I build it for everyone. I don't want them to avoid using it because of design issues. So, just like you have suggested. I will still keep the light design, but give users the possibility to change the style to dark or blue theme in hope that this might avoid users from using the website.

Thanks for your feedback and your honest review.

**Comment by ronmahiii** [comment]
Can someone help me? Whenever I try to access TopAnimeStream website, I/m directed to this site https://www.vhub.io/watch/TtrSH3fX2LwRRNvX?playlist=ybmxWWTWS2rbWOjm. What's going on? Also the Android App is not working.

Thanks in Advance!

**Comment by pepijn809** [comment]
@ronmahiii 
Hello!

**I suggest you read my reply on the following question of @Draxler.** 
https://github.com/senpaiski/TopAnimeStream/issues/30

I hereby request @senpaiski to close the following specified issues 'https://github.com/senpaiski/TopAnimeStream/issues/30 and https://github.com/senpaiski/TopAnimeStream/issues/27'.

**Comment by Draxler** [comment]
yea,, this one is for closure :(
