### ISSUE TITLE
Why can not sign up on your website? It keep prompting me to enter password.

### ISSUE THREAD

**Issue by deepnight36** [senpaiski/TopAnimeStream#9]
Why can not sign up on your website? It keep prompting me to enter password.

**Comment by senpaiski** [comment]
Whats your username?

**Comment by senpaiski** [comment]
Can you paste the exact error you are receiving or submit a screenshot?

**Comment by deepnight36** [comment]
![image](https://cloud.githubusercontent.com/assets/7659610/5791777/d15153e4-9f29-11e4-80a6-ff34d6beb23b.png)

as above screen capture, no matter how many times i enter the password, it still stop at this step, telling me to enter password. no extra information.

**Comment by senpaiski** [comment]
What the hell! The captcha is not showing!

![image](https://cloud.githubusercontent.com/assets/10069765/5797519/8c3951ca-9f89-11e4-9161-cd96b83ba824.png)

I think you don't have javascript enabled on your browser?

**Comment by deepnight36** [comment]
I see it today, :)

**Comment by senpaiski** [comment]
Sorry for the inconvenience. I will close the issue now. 

If you have other problems send me a private message on your TopAnimeStream account or create a post on the website forum.
